### ISSUE TITLE
versioning

### ISSUE THREAD

**Issue by IzzySoft** [gamemn02/Settings-Database-Provider#4]
Please don't forget to [update `versionCode` and `versionName`](https://github.com/gamemn02/Settings-Database-Provider/blob/main/app/build.gradle#L14) when making a new release. F-Droid won't pick up your second one, as CheckUpdates will complain ("`versionCode: 1`? I already have that."), and nobody using the app via my repo will receive any update notifications (nor will the new version be installed automatically, as Android will complain: "`versionCode: 1`? I already have that.").

**Comment by gamemn02** [comment]
Fixed. Thank you for notifying.

**Comment by IzzySoft** [comment]
Confirm the issue solved: new version was integrated properly, so F-Droid should pick it up soon as well. Thanks!
