### ISSUE TITLE
How to use it in another app?

### ISSUE THREAD

**Issue by pascua28** [gamemn02/Settings-Database-Provider#8]
So I've written an app but ever since updating to Android 14, I can't write to a setting anymore. Settings.System.putInt(context.getContentResolver(), "adaptive_fast_charging", 1); used to work on Android 13. I tried the Settings Database Editor without this app and it failed. But after installing this app, it successfully set the setting I need.
My question is how do I use it as a provider for my app? Thanks

**Comment by gamemn02** [comment]
You mean even after installing the package successfully in Android 14 without error? if not, try following solution from @lmore377: "The app needs to be installed thru adb with `adb install --bypass-low-target-sdk-block filename.apk`"

**Comment by pascua28** [comment]
> You mean even after installing the package successfully in Android 14 without error? if not, try following solution from @lmore377: "The app needs to be installed thru adb with `adb install --bypass-low-target-sdk-block filename.apk`"

What I mean is how to use this as a provider for another app that I wrote?

**Comment by gamemn02** [comment]
Settings.System.putInt() don't allow you to change the uri (may be it is possible by creating a contentresolver?), so instead I used:
```
val contentValues = ContentValues(2)
contentValues.put("name", key)
contentValues.put("value", value)
contentResolver.insert(Uri.parse("content://settings/system"), contentValues)
```
(in kotlin)
If i want to change to using the provider package, then i set the uri "content://settings/system" to "content://com.netvor.provider.SettingsDatabaseProvider/system"

you may also need to add following permissions to AndroidManifest:
```
<uses-permission android:name="com.netvor.settings.tables.provider.permission.SETTINGS_TABLES_PROVIDER" />
<queries>
    <provider android:authorities="com.netvor.provider.SettingsDatabaseProvider" />
</queries>
```

**Comment by pascua28** [comment]
> Settings.System.putInt() don't allow you to change the uri (may be it is possible by creating a contentresolver?), so instead I used:
> 
> ```
> val contentValues = ContentValues(2)
> contentValues.put("name", key)
> contentValues.put("value", value)
> contentResolver.insert(Uri.parse("content://settings/system"), contentValues)
> ```
> 
> (in kotlin) If i want to change to using the provider package, then i set the uri "content://settings/system" to "content://com.netvor.provider.SettingsDatabaseProvider/system"
> 
> you may also need to add following permissions to AndroidManifest:
> 
> ```
> <uses-permission android:name="com.netvor.settings.tables.provider.permission.SETTINGS_TABLES_PROVIDER" />
> <queries>
>     <provider android:authorities="com.netvor.provider.SettingsDatabaseProvider" />
> </queries>
> ```

Thanks. I realized that target sdk version needs to be set to 22 for it to work. Though simply setting the target sdk for my app works, it's a bit inconvenient to install an update so I opted out to using your app. Thank you

**Comment by gamemn02** [comment]
the problem with setting the target sdk to 22 is that you won't be able to publish on Google Play, but notice that even the provider package is inconvenient to install on Android 14 and you need adb for that. and also it could be a bit challenging to convince users that the provider package is totally safe to install. and also notice that if you want to modify secure and global tabels, you need to grant corresponding permission (WRITE_SECURE_SETTINGS) to the provider package instead of app
